load_paths:
  - src
  - test/src
  - test/vendor

logical_paths:
  - replicant.js
  - test.js
  - test.css

build:
  logical_paths:
    - turbolinks.js
  path: dist
  js_compressor: uglifier

require:
  - sprockets/export
